"""Add interes fechas en cliente

Revision ID: ad1f6567d293
Revises: 67d755eaa4d7
Create Date: 2025-12-15 23:35:01.351312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1f6567d293'
down_revision = '67d755eaa4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_interes_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proximo_interes_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proximo_pago_fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('proximo_pago_fecha')
        batch_op.drop_column('proximo_interes_fecha')
        batch_op.drop_column('ultimo_interes_fecha')

    # ### end Alembic commands ###
